version: '3'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "8080:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin

  publisher:
    build: ./publisher
    restart: always
    depends_on:
      - rabbitmq1

  consumer:
    build: ./consumer
    restart: always
    depends_on:
      - rabbitmq1
      - publisher

  consumer-fail:
    build: ./consumer-fail
    restart: always
    depends_on:
      - rabbitmq1
      - publisher

  # api-example:


    


